### ISSUE TITLE
Put each service in its own branch

### ISSUE THREAD

**Issue by MegaApuTurkUltra** [Scratch-Cloud-Services/scratch-cloud-services#1]
We should have each service in its own branch, and the master branch should contain only stable versions of each.

Pros:
- Minimal interference between commits, none of that annoying fast-forward/merge stuff that git always does when you're behind
- All services in a single (branches) menu
- People don't get unstable versions of scripts

Cons:
- _IDK yet_

**Comment by jeandrek** [comment]
Sounds good

**Comment by BookOwl** [comment]
OK

**Comment by jeandrek** [comment]
So separate branches will just contain that service, and they get merged to master for every release of that service?
(idk actually how to have branches that just have some files but when merged don't delete other files)

**Comment by MegaApuTurkUltra** [comment]
Maybe master can just contain a readme that links to all the branches and stable versions? IDK. There really shouldn't be merge issues assuming people don't release very quickly.

**Comment by ghost** [comment]
+1

Also every branch must contain a package.json for easy install

**Comment by jeandrek** [comment]
@jayforsythe <sub>(oh cool gh has this :stuck_out_tongue:)</sub> like in NPM?

**Comment by ghost** [comment]
@Jonathan50 yes; what else?

**Comment by jeandrek** [comment]
@jayforsythe How do you install a package that isn't in the NPM registry?

**Comment by ghost** [comment]
You acquire it from github or something else, run `npm install` and you're off.

By "install" I mean install dependencies, build, etc.

**Comment by jeandrek** [comment]
Ok, but `npm` doesn't know what package you want to install :package:
Do you `cd my_package` first?

edit:

> `npm` doesn't know what :package: you want to install

**Comment by ghost** [comment]
of course. you always have to cd into it. when did i say that you didn't? :P 

all `npm install` does it run the install scripts, which install the dependencies, etc... not having a package.json means you have to go through and look at all the libraries used. if you run `npm install` then it will read all the dependencies from package.json and install them automatically.

**Comment by jeandrek** [comment]
So if we do it like that, then probably all services should be available as NPM modules, even ones which aren't Node.js (as they can have NPM modules to, NPM is a bit like .deb s with `apt` and `dpkg`)

**Comment by jeandrek** [comment]
@MegaApuTurkUltra

> Maybe master can just contain a readme that links to all the branches and stable versions? IDK. There really shouldn't be merge issues assuming people don't release very quickly.

:+1:
That's a good idea. It can link to the branch and SHA-1 hash, or to the release page.

**Comment by jeandrek** [comment]
So to add a service, would I do

``` bash
git checkout -b s2ssh
mkdir s2ssh
cd s2ssh
cp ~/Scratch/s2ssh.js .
gedit README.md # i use gedit
```

**Comment by BookOwl** [comment]
I don't know. I've only used the gui.

**Comment by jeandrek** [comment]
@BookOwl

> I don't know. I've only used the gui.

That is creating and switching to a new branch, making a folder called s2ssh, going into that folder, putting s2ssh.js in their and editing README.md

**Comment by jeandrek** [comment]
@jayforsythe @BookOwl 

> +1
> 
> Also every branch must contain a package.json for easy install

I'm reading https://docs.npmjs.com/files/package.json , apparently packages can be scoped like `@myorg/mypackage`, should there be a namespace for scratch-cloud-services?

**Comment by ghost** [comment]
@Jonathan50 
I don't think that's necessary to publish anything on npm, as this will probably be a small project. All I meant by including a package.json was for info about dependencies so users can easily install dependencies using `npm install`, and maybe some repository info.

**Comment by jeandrek** [comment]
@jayforsythe 

> @Jonathan50 
> I don't think that's necessary to publish anything on npm, as this will probably be a small project. All I meant by including a package.json was for info about dependencies so users can easily install dependencies using `npm install`, and maybe some repository info.

I know that, I never implied we would/should publish anything on the NPM registry.

**Comment by ghost** [comment]
> @jayforsythe
> 
> > @Jonathan50
> > I don't think that's necessary to publish anything on npm, as this will probably be a small project. All I meant by including a package.json was for info about dependencies so users can easily install dependencies using npm install, and maybe some repository info.
> 
> I know that, I never implied we would/should publish anything on the NPM registry.

not trying to be rude here, but why would a scope be necessary if we're not publishing them?

**Comment by jeandrek** [comment]
@jayforsythe

> > @jayforsythe
> > 
> > > @Jonathan50
> > > I don't think that's necessary to publish anything on npm, as this will probably be a small project. All I meant by including a package.json was for info about dependencies so users can easily install dependencies using npm install, and maybe some repository info.
> > 
> > I know that, I never implied we would/should publish anything on the NPM registry.
> 
> not trying to be rude here, but why would a scope be necessary if we're not publishing them?

It is _possible_ (although rather unlikely) users may have packages with the same names.
Putting it in a scope prevents collisions.
It'll **probably** be fine without though.

**Comment by jeandrek** [comment]
This should probably be closed now.

**Comment by BookOwl** [comment]
OK
