### ISSUE TITLE
How will releases work?

### ISSUE THREAD

**Issue by jeandrek** [Scratch-Cloud-Services/scratch-cloud-services#2]
How will releases work? Will different services make a release with all services using latest stable versions of each, or will something different happen? Maybe releases will only be made when stable versions of each have completed? Maybe there won't be releases at all, and users can clone the repository or install a tarball for each separate service?
- [x] Decide how releases work and if there will be releases

**Comment by jeandrek** [comment]
Maybe we make a release every time a branch is merged into master?

**Comment by jeandrek** [comment]
btw don't run s2ssh until we've made sure there are 

## **NO**

vulnerabilities.
Only run stable versions and always stay up-to-date.

Also when should I merge [s2ssh](/Scratch-Cloud-Services/scratch-cloud-services/tree/s2ssh)?

**Comment by jeandrek** [comment]
@BookOwl @MegaApuTurkUltra @jayforsythe @as-com

**Comment by ghost** [comment]
Are releases really needed? I thought this was going to be a collection of scripts that run small Scratch servers.

**Comment by MegaApuTurkUltra** [comment]
^

**Comment by jeandrek** [comment]
@BookOwl do you agree?

**Comment by towerofnix** [comment]
@jayforsythe ^

**Comment by BookOwl** [comment]
I agree with @jayforsythe. Releases aren't really needed, in my opinion.

**Comment by as-com** [comment]
I think there should be a separate repo for each script. Some of them can
get pretty complicated.

**Comment by PolyEdge** [comment]
Could I join?

**Comment by jeandrek** [comment]
Ok then :smile:
Does anyone agree with @as-com ?
